openapi: 3.1.0
info:
  title: adyd_openapi
  description: open api adyd
  version: 1.0.0
servers:
  - url: 'api'
paths:
  /campaign:
    get:
      summary: Get all campaigns
      operationId: getAllCampaign
      tags:
        - campaign-controller
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CampaignDto'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDto'
    post:
      summary: create new campaign
      operationId: createCampaign
      tags:
        - campaign-controller
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CampaignDto'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignDto'
  /campaign/{campaignId}:
    get:
      summary: get campaign by id
      operationId: getCampaignById
      tags:
        - campaign-controller
      parameters:
        - name: campaignId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignDto'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundDto'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDto'
    patch:
      summary: update campaign
      operationId: updateCampaign
      tags:
        - campaign-controller
      parameters:
        - name: campaignId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CampaignDto'
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignDto'
  /campaign/{campaignId}/race:
    get:
      summary: get all available races for campaign
      operationId: getRaceByCampaignId
      tags:
        - campaign-controller
      parameters:
        - name: campaignId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignRaceDto'
  /campaign/{campaignId}/player-class:
    get:
      summary: get all available player classes for campaign
      operationId: getPlayerClassForCampaign
      tags:
        - campaign-controller
      parameters:
        - name: campaignId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignPlayerClassDto'
  /campaign/{campaignId}/player-class/{playerClassId}:
    post:
      summary: add relation between player class and campaign
      operationId: addPlayerClassInCampaign
      tags:
        - campaign-controller
      parameters:
        - name: campaignId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: playerClassId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignPlayerClassDto'
  /campaign/{campaignId}/race/{raceId}:
    post:
      summary: add relation between race and campaign
      operationId: addRaceInCampaign
      tags:
        - campaign-controller
      parameters:
        - name: campaignId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: raceId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        202:
          description: accepted
        404:
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundDto'
    delete:
      summary: delete relation between race and campaign
      operationId: deleteRaceInCampaign
      tags:
        - campaign-controller
      parameters:
        - name: campaignId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: raceId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        202:
          description: accepted
        404:
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundDto'
  /race:
    get:
      summary: get all races
      operationId: getAllRaces
      tags:
        - race-controller
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RaceDto'
    post:
      summary: add new race
      operationId: createNewRace
      tags:
        - race-controller
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RaceDto'
      responses:
        201:
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaceDto'
  /race/{raceId}:
    delete:
      summary: delete race
      operationId: deleteRace
      tags:
        - race-controller
      parameters:
        - name: raceId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: No Content
    patch:
      summary: modify race
      operationId: modifyRace
      tags:
        - race-controller
      parameters:
        - name: raceId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RaceDto'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaceDto'
        404:
          description: Not found
    get:
      summary: get race by id
      tags:
        - race-controller
      operationId: getRaceById
      parameters:
        - name: raceId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaceDto'
        404:
          description: Not found
  /race/{raceId}/characteristic:
    get:
      summary: race by id characteristics to create a character
      operationId: getRaceCharacteristicsById
      tags:
        - race-characteristic-controller
      parameters:
        - name: raceId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaceCharacteristicDto'
        404:
          description: Not found
    post:
      summary: add characteristic to race
      operationId: addCharacteristicToRace
      tags:
        - race-characteristic-controller
      parameters:
        - name: raceId
          in: path
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CharacteristicDto'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaceDto'
        404:
          description: Not found
  /race/builtin:
    get:
      summary: get built in characteristics name
      operationId: getBuiltInCharacteristics
      tags:
        - race-characteristic-controller
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuiltInDto'
  /characteristic:
    post:
      summary: create a new built-in characteristic
      operationId: createNewCharacteristic
      tags:
        - characteristic-controller
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CharacteristicDto'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CharacteristicDto'

  /player-class:
    get:
      summary: get all player class
      operationId: getAllPlayerClass
      tags:
        - player-class-controller
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlayerClassDto'
    post:
      summary: create a new player class
      operationId: createNewPlayerClass
      tags:
        - player-class-controller
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayerClassDto'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerClassDto'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
  /player-class/{playerClassId}:
    get:
      summary: get player class by id
      operationId: getPlayerClassById
      tags:
        - player-class-controller
      parameters:
        - name: playerClassId
          in: path
          required: true
          description: player class id
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerClassDto'
        404:
          description: Not found
    delete:
      summary: delete player class by id
      operationId: deletePlayerClassById
      tags:
        - player-class-controller
      parameters:
        - name: playerClassId
          in: path
          required: true
          description: player class id
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: OK
components:
  schemas:
    PlayerClassDto:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        hitDice:
          type: string
    RaceDto:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    CampaignDto:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    CampaignRaceDto:
      type: object
      required:
        - campaign
        - races
      properties:
        campaign:
          type: string
        races:
          type: array
          items:
            $ref: '#/components/schemas/RaceDto'
    CampaignPlayerClassDto:
      type: object
      required:
        - campaign
        - playerClass
      properties:
        campaign:
          type: string
        playerClass:
          type: array
          items:
            $ref: '#/components/schemas/PlayerClassDto'
    RaceCharacteristicDto:
      type: object
      required:
        - race
        - characteristic
      properties:
        race:
          $ref: '#/components/schemas/RaceDto'
        characteristic:
          type: array
          items:
            $ref: '#/components/schemas/CharacteristicDto'
    CharacteristicDto:
      type: object
      required:
        - name
        - code
        - shortDescription
        - type
        - value
      properties:
        code:
          type: string
        name:
          type: string
        value:
          type: string
        shortDescription:
          type: string
        description:
          type: string
        type:
          type: string
          enum:
            - STRING
            - INTEGER
            - BOOLEAN
        symbol:
          type: string
          enum:
            - BONUS
            - MALUS
            - NONE
    BuiltInDto:
      type: array
      items:
        type: string
    NotFoundDto:
      type: object
      properties:
        message:
          type: string
    BadRequest:
      type: object
      properties:
        message:
          type: string
    InternalServerErrorDto:
      type: object
      properties:
        message:
          type: string
