server:
  port: 10000
  servlet:
    context-path: /api
spring:
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      idle-timeout: 60000
      leak-detection-threshold: 2000
      jdbc-url: ${DB_URL:jdbc:postgresql://localhost:5433/postgres}
      username: ${USER_NAME:postgres}
      password: ${PASS:pass4postgres}
      driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

